version: '3.8'
services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-blog-app
    container_name: laravel-blog-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: laravel-blog-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: laravel-blog-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-test}
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "33061:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
